export default {
	'navbar.items.btn1': 'What is caipi?',
	'navbar.items.btn2': 'Benefits',
	'navbar.items.btn4': 'Contact us',
	'navbar.items.btn5': 'Login',
	'navbar.items.terminos': 'Terms',
	'hero.title.part1': 'OPERATE BETWEEN',
	'hero.title.argentina': 'ARGENTINA',
	'hero.title.part2': 'AND',
	'hero.title.brasil': 'BRAZIL',
	'hero.title.part3': 'WITHOUT COMPLICATIONS',
	'hero.empresa.text1': 'With',
	'hero.empresa.caipiEmpresa': 'CAIPI BUSINESS',
	'hero.empresa.text2': 'you manage',
	'hero.empresa.text3': 'your commercial operations.',
	'hero.empresa.button': 'BUSINESS LOGIN',
	'hero.app.text1': 'Travel, pay and transfer via',
	'hero.app.pix': 'PIX',
	'hero.app.text2': 'without hassle.',
	'hero.app.text3': 'Do it all with',
	'hero.app.caipiApp': 'CAIPI APP',
	'hero.app.button': 'DOWNLOAD CAIPI',
	'hero.backgroundTitle': 'Pix sent!',
	'hero.backgroundSubtitle': 'Successful transfer',
	'discover.title': 'Discover caipi',
	'discover.paragraph1': 'Web app solution for <span class="font-gothamBlack">businesses</span>.',
	'discover.paragraph2':
		'Caipi converts Argentine pesos and Brazilian reais <span class="font-gothamBlack">instantly</span> <br /> <span class="font-gothamBlack">without fees</span> and at the best exchange rate.',
	'discover.useCaipi': 'I want to use caipi',
	'discover.useCaipiEnterprise': 'I want to use caipi in my company',
	'benefits.title': 'Want to know the benefits of Caipi?',
	'benefits.cards.0.title': 'Security in Transactions',
	'benefits.cards.0.description':
		'Enjoy secure and reliable payments, backed by cutting-edge technology.',
	'benefits.cards.1.title': 'Time and Effort Savings',
	'benefits.cards.1.description':
		'Simplify the process of sending money to Brazil, avoiding cumbersome procedures and delays.',
	'benefits.cards.2.title': 'Automatic Currency Exchange',
	'benefits.cards.2.description':
		'Get the best exchange rate available in real time, without taxes and without commissions.',
	'benefits.cards.3.title': 'Ease of Use',
	'benefits.cards.3.description':
		'The solution is intuitive and easy to use, allowing for quick and hassle-free payments.',
	'benefits.cards.4.title': 'Banking Compatibility',
	'benefits.cards.4.description':
		'Works with any bank in Argentina, providing flexibility and convenience.',
	'form.title': 'Company contact form',
	'form.name': 'Name',
	'form.email': 'E-mail',
	'form.phone': 'Phone',
	'form.category': 'Category',
	'form.country': 'Select country',
	'form.button': 'Send!',
	'doubts.title.part1': 'Still have ',
	'doubts.title.part2': 'doubts?',
	'doubts.subtitle1': 'We are always available',
	'doubts.subtitle2': 'Get in touch with us!',
	'footer.subtitle': 'All rights reserved.'
};
