export default {
	loginEmailLabel: 'Email',
	loginEmailPlaceholder: 'name@enterprise.com',
	loginPasswordLabel: 'Password',
	loginForgotPassword: 'Forgot your password?',
	loginBtn: 'Login',
	loginInvalidCredentials: 'Invalid credentials',
	// Restore password translations
	restorePasswordTitle: 'Restore password',
	restorePasswordSubtitle: 'Enter your email to receive recovery instructions',
	restorePasswordEmailLabel: 'Email',
	restorePasswordEmailPlaceholder: 'name@enterprise.com',
	restorePasswordBtn: 'Send instructions',
	restorePasswordSuccess: 'Instructions have been sent to your email',
	restorePasswordError: 'Error sending instructions',
	restorePasswordEmailError: 'Please verify that your email is correctly written',
	restorePasswordBackToLogin: 'Back to login',
	emailRequired: 'Email is required',
	// Change password translations
	changePasswordTitle: 'Change password',
	changePasswordSubtitle: 'Enter your new password',
	changePasswordNewLabel: 'New password',
	changePasswordConfirmLabel: 'Confirm password',
	changePasswordBtn: 'Change password',
	changePasswordSuccess: 'Password changed successfully',
	changePasswordError: 'Error changing password',
	changePasswordBackToLogin: 'Back to login',
	passwordRequired: 'Password is required',
	confirmPasswordRequired: 'Confirm password is required',
	passwordMismatch: 'Passwords do not match',
	tokenRequired: 'Authorization token required',
	// Confirm email translations
	confirmEmailTitle: 'Confirm email',
	confirmEmailSuccess: 'Email confirmed successfully',
	confirmEmailError: 'Error confirming email',
	confirmEmailSuccessMessage: 'Your email has been confirmed. You can now log in to your account.',
	confirmEmailErrorMessage: 'There was an error confirming your email. Please try again or contact support.',
	confirmEmailRedirectMessage: 'You will be redirected to login in a few seconds...',
	confirmEmailGoToLogin: 'Go to login',
	confirmEmailGoToHome: 'Go to home'
};
