export default {
	newPaymentBreadcrumb: 'New',
	newPaymentDestinationAccount: 'Destination account: PIX / CNPJ *',
	newPaymentSourceCurrency: 'Source currency',
	newPaymentDestinationCurrency: 'Destination currency',
	newPaymentValueToReceive: 'Value to receive',
	newPaymentPair: 'Origin -> Dest. currency',
	newPaymentType: 'Type',
	newPaymentClientNameReference: 'Client name',
	newPaymentClientEmailReference: 'Client email',
	newPaymentClientPhoneReference: 'Client phone',
	newPaymentCodeReference: 'Reference code',
	newPaymentConceptReference: 'Concept',
	newPaymentFileReference: 'File',
	newPaymentGenerateBtn: 'Generate payment link',
	newPaymentOkBtn: 'Ok',
	newPaymentSuccess: 'Payment created',
	newPaymentSourceCurrencyMissing: 'Source currency is required',
	newPaymentDestinationCurrencyMissing: 'Destination currency is required',
	newPaymentInvalidAmount: 'Enter a valid amount to receive',
	newPaymentEmailPagador: 'Payer email',
	newPaymentCpfPagador: 'Payer cpf',
	newPaymentExpirationMsg: "The QR expires in {minutes}m {seconds}s.",
	newPaymentQrBtn: "Generate QR",
	newPaymentCuil: "Payer's CUIL/CUIT",
};
