export default {
	paymentsBreadcrumb: 'Transactions',
	newPaymentBtn: 'Generate New Charge / Payment',
	exportDataBtn: 'Export Data',
	paymentsSearchPlaceholder: 'Search by customer',
	statusFilter: 'Filter by status',
	orderLabel: 'Ordering',
	orderPlaceholder: 'Select the ordering',
	filterLabel: 'Filtering',
	dateFilterFrom: 'From',
	dateFilterTo: 'To',
	paymentsTableHeadersId: 'ID',
	paymentsTableHeadersCreatedAt: 'Date',
	paymentsTableHeadersEstado: 'Status',
	paymentsTableHeadersCliente: 'Client',
	paymentsTableHeadersRef: 'Reference',
	paymentsTableHeadersConc: 'Concept',
	paymentsTableHeadersMonedaDestino: 'Currency to receive',
	paymentsTableHeadersMontoDestino: 'Value to receive',
	paymentsTableHeadersCuenta: 'Account',
	paymentsTableHeadersRefCodigo: 'Ref. code',
	paymentsTableHeadersRefNombreCliente: 'Ref. customer name',
	paymentsTableActions: 'Actions',
	paymentsTablePaymentStatesPending: 'pending',
	paymentsTablePaymentStatesProcessing: 'processing',
	paymentsTablePaymentStatesFinished: 'finished',
	paymentsTablePaymentStatesRejected: 'rejected',
	paymentsTablePaymentStatesCanceled: 'canceled',

	// QR Payments translations
	qrPaymentsBreadcrumb: 'QR Charges',
	createQrPaymentBtn: 'Create QR Charge',
	viewQrModalTitle: 'View QR',
	createQrModalTitle: 'Create New QR Charge',
	qrPaymentsSearchPlaceholder: 'Search QR charges',
	qrPaymentsTableHeadersId: 'ID',
	qrPaymentsTableHeadersEstado: 'Status',
	qrPaymentsTableHeadersMonto: 'Amount',
	qrPaymentsTableHeadersMoneda: 'Currency',
	qrPaymentsTableHeadersCreatedAt: 'Date',
	qrPaymentsTableHeadersCliente: 'Customer',
	qrPaymentsTableHeadersConcepto: 'Concept',
	qrPaymentsTableHeadersReferencia: 'Reference',
	qrPaymentsTableEstadoProceso: 'processing',
	qrPaymentsTableEstadoFinalizado: 'finished',
	qrPaymentsTableEstadoCancelado: 'canceled',
	qrPaymentsTableEstadoRechazado: 'rejected',
	qrPaymentsTableEstadoUsdtReceived: 'USDT received',
	qrPaymentsTableEstadoSwapExecuted: 'Swap executed',
	qrPaymentsTableEstadoWithdrawal: 'Withdrawal processed',
	createQrAmountLabel: 'Charge amount',
	createQrConceptLabel: 'Concept',
	createQrConceptPlaceholder: 'Charge description',
	cancelBtn: 'Cancel',
	createQrBtn: 'Create charge',

	// QR translations
	showQrBtn: 'Show QR',
	qrGenerating: 'Generating QR...',
	qrGenerateSuccess: 'QR generated successfully',
	qrGenerateError: 'Error generating QR',
	qrConcept: 'Charge QR',
	qrReference: 'Reference',
	qrVariableAmount: 'Amount defined by customer',
	qrPrintButton: 'Print QR',
	qrPrintTitle: 'Print QR',
	qrPrintError: 'Error opening print window',

	// Static QR translations
	staticQrMontoPesos: 'Amount (Pesos)',
	staticQrMontoReales: 'Amount (Reais)',
	staticQrMontoUsdt: 'Amount (USDT)',
	staticQrEstadoPendiente: 'pending',
	staticQrEstadoProceso: 'processing',
	staticQrEstadoFinalizado: 'finished',
	staticQrEstadoCancelado: 'canceled',
	staticQrEstadoError: 'error',
	qrPaymentsTableHeadersEmpresa: 'Company',
	acceptBtn: 'Accept',
	paymentCancelled: 'Payment cancelled',
	errorCancellingPayment: 'Error cancelling payment',
	paymentSuccess: 'Payment successful',
	paymentFailed: 'Payment failed',
	closeModal: 'Close',
	cancelPayment: 'Cancel payment',
	waitingPayment: 'Waiting for payment...',
	processing: 'Processing...',
	viewPaymentDetails: 'View details',
	cannotCancelPayment: 'Only pending payments can be cancelled',
	paymentDetails: 'Payment details',
	backToList: 'Back to list'
};
