export default {
	profileBreadcrumb: 'Profile',
	profileEnterpriseLabel: 'Enterprise',
	profileEnterpriseName: 'Name',
	profileAddress: 'Address',
	profilePhone: 'Phone',
	profileAccounts: 'Bank Accounts',
	profileEmailLabel: 'Email',
	profileNamesLabel: 'Names',
	profilePassword: 'Password',
	profileRepeatPassword: 'Repeat Password',
	profileSendBtn: 'Send',
	profileBtn: 'Profile',
	profileLogoutBtn: 'Log out',
	profileSuccess: 'Profile edited',
	profileRepeatPasswordError: 'Passwords do not match',
	profileUserLabel: "User detail",
	profileChangePassword: "Change password",
	profileBankName: 'Bank Name',
	profileNoAccounts: 'There are no associated accounts.',
	profileChangeCallback: "Edit",
	profileChangeApiKey: "Generate new API key",
	profileConfirmTitle: "Generate",
	profileConfirmSubtitle: "Are you sure you want to generate a new API key?",

};
