export default {
	'navbar.items.btn1': 'O que é caipi?',
	'navbar.items.btn2': 'Benefícios',
	'navbar.items.btn3': 'Sobre nós',
	'navbar.items.btn4': 'Contate-nos',
	'navbar.items.btn5': 'Entrar',
	'navbar.items.terminos': 'Termos',
	'hero.title.part1': 'OPERE ENTRE',
	'hero.title.argentina': 'ARGENTINA',
	'hero.title.part2': 'E',
	'hero.title.brasil': 'BRASIL',
	'hero.title.part3': 'SEM COMPLICAÇÕES',
	'hero.empresa.text1': 'Com',
	'hero.empresa.caipiEmpresa': 'CAIPI EMPRESA',
	'hero.empresa.text2': 'você gerencia',
	'hero.empresa.text3': 'suas operações comerciais.',
	'hero.empresa.button': 'ACESSO PARA EMPRESAS',
	'hero.app.text1': 'Viaje, pague e transfira por',
	'hero.app.pix': 'PIX',
	'hero.app.text2': 'sem complicar.',
	'hero.app.text3': 'Faça tudo com',
	'hero.app.caipiApp': 'CAIPI APP',
	'hero.app.button': 'BAIXAR CAIPI',
	'hero.backgroundTitle': 'Pix enviado!',
	'hero.backgroundSubtitle': 'Transferência bem-sucedida',
	'discover.title': 'Descubra caipi',
	'discover.paragraph1':
		'Solução de aplicativo web para <span class="font-gothamBlack">empresas</span>.',
	'discover.paragraph2':
		'Caipi converte pesos argentinos e reais brasileiros <span class="font-gothamBlack">instantaneamente</span> <br /> <span class="font-gothamBlack">sem taxas</span> e na melhor taxa de câmbio.',
	'discover.useCaipi': 'Quero usar caipi',
	'discover.useCaipiEnterprise': 'Quero usar caipi na minha empresa',
	'benefits.title': 'Quer saber os benefícios da Caipi?',
	'benefits.cards.0.title': 'Segurança nas Transações',
	'benefits.cards.0.description':
		'Aproveite pagamentos seguros e confiáveis, respaldados por tecnologia de ponta.',
	'benefits.cards.1.title': 'Economia de Tempo e Esforço',
	'benefits.cards.1.description':
		'Simplifique o envio de dinheiro para o Brasil, evitando procedimentos complicados e atrasos.',
	'benefits.cards.2.title': 'Câmbio Automático de Moeda',
	'benefits.cards.2.description':
		'Obtenha a melhor taxa de câmbio disponível em tempo real, sem impostos e sem comissões.',
	'benefits.cards.3.title': 'Facilidade de Uso',
	'benefits.cards.3.description':
		'A solução é intuitiva e fácil de usar, permitindo pagamentos rápidos e sem complicações.',
	'benefits.cards.4.title': 'Compatibilidade Bancária',
	'benefits.cards.4.description':
		'Funciona com qualquer banco na Argentina, proporcionando flexibilidade e conveniência.',
	'form.title': 'Formulário contato empresa',
	'form.name': 'Nome',
	'form.email': 'E-mail',
	'form.phone': 'Telefone',
	'form.category': 'Categoria',
	'form.country': 'Selecione o país',
	'form.button': 'Enviar!',
	'doubts.title.part1': 'Ainda tem ',
	'doubts.title.part2': 'dúvidas?',
	'doubts.subtitle1': 'Estamos sempre disponíveis',
	'doubts.subtitle2': 'Entre em contato conosco!',
	'footer.subtitle': 'Todos os direitos reservados.'
};
