export default {
	loginEmailLabel: 'Email',
	loginEmailPlaceholder: 'nome@empresa.com',
	loginPasswordLabel: 'Senha',
	loginForgotPassword: 'Recuperar senha?',
	loginBtn: 'Entrar',
	loginInvalidCredentials: 'Credenciais inválidas',
	// Restore password translations
	restorePasswordTitle: 'Recuperar senha',
	restorePasswordSubtitle: 'Digite seu email para receber instruções de recuperação',
	restorePasswordEmailLabel: 'Email',
	restorePasswordEmailPlaceholder: 'nome@empresa.com',
	restorePasswordBtn: 'Enviar instruções',
	restorePasswordSuccess: 'Instruções foram enviadas para seu email',
	restorePasswordError: 'Erro ao enviar instruções',
	restorePasswordEmailError: 'Verifique se seu email está escrito corretamente',
	restorePasswordBackToLogin: 'Voltar ao login',
	emailRequired: 'Email é obrigatório',
	// Change password translations
	changePasswordTitle: 'Alterar senha',
	changePasswordSubtitle: 'Digite sua nova senha',
	changePasswordNewLabel: 'Nova senha',
	changePasswordConfirmLabel: 'Confirmar senha',
	changePasswordBtn: 'Alterar senha',
	changePasswordSuccess: 'Senha alterada com sucesso',
	changePasswordError: 'Erro ao alterar senha',
	changePasswordBackToLogin: 'Voltar ao login',
	passwordRequired: 'Senha é obrigatória',
	confirmPasswordRequired: 'Confirmar senha é obrigatório',
	passwordMismatch: 'As senhas não coincidem',
	tokenRequired: 'Token de autorização obrigatório',
	// Confirm email translations
	confirmEmailTitle: 'Confirmar email',
	confirmEmailSuccess: 'Email confirmado com sucesso',
	confirmEmailError: 'Erro ao confirmar email',
	confirmEmailSuccessMessage: 'Seu email foi confirmado. Você já pode fazer login na sua conta.',
	confirmEmailErrorMessage: 'Houve um erro ao confirmar seu email. Tente novamente ou entre em contato com o suporte.',
	confirmEmailRedirectMessage: 'Você será redirecionado para o login em alguns segundos...',
	confirmEmailGoToLogin: 'Ir para login',
	confirmEmailGoToHome: 'Ir para início'
};
