export default {
	newPaymentBreadcrumb: 'Novo',
	newPaymentDestinationAccount: 'Conta de destino',
	newPaymentSourceCurrency: 'Moeda de origem',
	newPaymentDestinationCurrency: 'Moeda de destino',
	newPaymentValueToReceive: 'Valor a receber',
	newPaymentPair: 'Moeda origem -> destino',
	newPaymentType: 'Tipo',
	newPaymentClientNameReference: 'Nome cliente',
	newPaymentClientEmailReference: 'Email cliente',
	newPaymentClientPhoneReference: 'Telefone cliente',
	newPaymentCodeReference: 'Código referência',
	newPaymentConceptReference: 'Conceito',
	newPaymentFileReference: 'Arquivo',
	newPaymentGenerateBtn: 'Gerar link de pagamento',
	newPaymentOkBtn: 'Terminar',
	newPaymentSuccess: 'Pagamento criado',
	newPaymentSourceCurrencyMissing: 'Selecione uma moeda de origem',
	newPaymentDestinationCurrencyMissing: 'Selecione uma moeda de destino',
	newPaymentInvalidAmount: 'Insira um valor a receber válido',
	newPaymentEmailPagador: 'Email do pagador',
	newPaymentCpfPagador: 'CPF Email do pagador',
	newPaymentExpirationMsg: "O QR expira em {minutes}m {seconds}s.",
	newPaymentQrBtn: "Gerar QR",
	newPaymentCuil: "CUIL/CUIT do pagador",
};
