export default {
	paymentsBreadcrumb: 'Transações',
	newPaymentBtn: 'Gerar Novo Cobrança / Pagamento',
	showFilters: 'Mostrar filtros',
	hideFilters: 'Ocultar filtros',
	exportDataBtn: 'Exportar Dados',
	paymentsSearchPlaceholder: 'Pesquisar por clinte',
	statusFilter: 'Filtrar por status',
	orderLabel: 'Ordenação',
	orderPlaceholder: 'Seleccione a ordenação',
	filterLabel: 'Filtragem',
	dateFilterFrom: 'De',
	dateFilterTo: 'Até',
	paymentsTableHeadersId: 'ID',
	paymentsTableHeadersCreatedAt: 'Data',
	paymentsTableHeadersEstado: 'Status',
	paymentsTableHeadersMonedaDestino: 'Moeda a receber',
	paymentsTableHeadersMontoDestino: 'Valor a receber',
	paymentsTableHeadersCliente: 'Cliente',
	paymentsTableHeadersRef: 'referência',
	paymentsTableHeadersConc: 'Conceito',
	paymentsTableHeadersCuenta: 'Conta',
	paymentsTableHeadersRefCodigo: 'Ref. código',
	paymentsTableHeadersRefNombreCliente: 'Ref. nome cliente',
	paymentsTableActions: 'Ações',
	paymentsTablePaymentStatesPending: 'pendente',
	paymentsTablePaymentStatesProcessing: 'processo',
	paymentsTablePaymentStatesFinished: 'finalizado',
	paymentsTablePaymentStatesRejected: 'rejeitado',
	paymentsTablePaymentStatesCanceled: 'cancelado',

	// QR Payments translations
	qrPaymentsBreadcrumb: 'Cobranças QR',
	createQrPaymentBtn: 'Criar Cobrança QR',
	viewQrModalTitle: 'Visualizar QR',
	createQrModalTitle: 'Criar Nova Cobrança QR',
	qrPaymentsSearchPlaceholder: 'Pesquisar cobranças QR',
	qrPaymentsTableHeadersId: 'ID',
	qrPaymentsTableHeadersEstado: 'Status',
	qrPaymentsTableHeadersMonto: 'Valor',
	qrPaymentsTableHeadersMoneda: 'Moeda',
	qrPaymentsTableHeadersCreatedAt: 'Data',
	qrPaymentsTableHeadersCliente: 'Cliente',
	qrPaymentsTableHeadersConcepto: 'Conceito',
	qrPaymentsTableHeadersReferencia: 'Referência',
	qrPaymentsTableEstadoProceso: 'processo',
	qrPaymentsTableEstadoFinalizado: 'finalizado',
	qrPaymentsTableEstadoCancelado: 'cancelado',
	qrPaymentsTableEstadoRechazado: 'rejeitado',
	qrPaymentsTableEstadoUsdtReceived: 'USDT recebido',
	qrPaymentsTableEstadoSwapExecuted: 'Swap executado',
	qrPaymentsTableEstadoWithdrawal: 'Saque realizado',
	createQrAmountLabel: 'Valor da cobrança',
	createQrConceptLabel: 'Conceito',
	createQrConceptPlaceholder: 'Descrição da cobrança',
	cancelBtn: 'Cancelar',
	createQrBtn: 'Criar cobrança',

	// QR translations
	showQrBtn: 'Mostrar QR',
	qrGenerating: 'Gerando QR...',
	qrGenerateSuccess: 'QR gerado com sucesso',
	qrGenerateError: 'Erro ao gerar QR',
	qrConcept: 'QR de Cobrança',
	qrReference: 'Referência',
	qrVariableAmount: 'Valor definido pelo cliente',
	qrPrintButton: 'Imprimir QR',
	qrPrintTitle: 'Imprimir QR',
	qrPrintError: 'Erro ao abrir janela de impressão',

	// Static QR translations
	staticQrMontoPesos: 'Valor (Pesos)',
	staticQrMontoReales: 'Valor (Reais)',
	staticQrMontoUsdt: 'Valor (USDT)',
	staticQrEstadoPendiente: 'pendente',
	staticQrEstadoProceso: 'processo',
	staticQrEstadoFinalizado: 'finalizado',
	staticQrEstadoCancelado: 'cancelado',
	staticQrEstadoError: 'erro',
	qrPaymentsTableHeadersEmpresa: 'Empresa',
	acceptBtn: 'Aceitar',
	paymentCancelled: 'Pagamento cancelado',
	errorCancellingPayment: 'Erro ao cancelar pagamento',
	paymentSuccess: 'Pagamento bem-sucedido',
	paymentFailed: 'Pagamento falhou',
	closeModal: 'Fechar',
	cancelPayment: 'Cancelar pagamento',
	waitingPayment: 'Aguardando pagamento...',
	processing: 'Processando...',
	viewPaymentDetails: 'Ver detalhes',
	cannotCancelPayment: 'Apenas pagamentos pendentes podem ser cancelados',
	paymentDetails: 'Detalhes do pagamento',
	backToList: 'Voltar à lista'
};
