export default {
	profileBreadcrumb: 'Perfil',
	profileEnterpriseLabel: 'Empresa',
	profileEnterpriseName: 'Nome',
	profileAddress: 'Endereço',
	profilePhone: 'Telefone',
	profileAccounts: 'Contas bancárias',
	profileEmailLabel: 'Email',
	profileNamesLabel: 'Nomes',
	profilePassword: 'Senha',
	profileRepeatPassword: 'Repetir Senha',
	profileSendBtn: 'Enviar',
	profileBtn: 'Perfil',
	profileLogoutBtn: 'Sair',
	profileSuccess: 'Perfil atualizado',
	profileRepeatPasswordError: 'As senhas não coincidem',
	profileUserLabel: "Detalhe do usuário",
	profileChangePassword: "Alterar a senha",
	profileBankName: 'Nome do banco',
	profileNoAccounts: 'Não há contas associadas.',
	profileChangeCallback: "Editar",
	profileChangeApiKey: "Gerar nova chave de API",
	profileConfirmTitle: "Gerar",
	profileConfirmSubtitle: "Você tem certeza de que deseja gerar uma nova chave de API?",
};
