export default {
	'navbar.items.btn1': '¿Qué es caipi?',
	'navbar.items.btn2': 'Beneficios',
	'navbar.items.btn4': 'Contactanos',
	'navbar.items.btn5': 'Ingresar',
	'navbar.items.terminos': 'Términos',
	'hero.title.part1': 'OPERÁ ENTRE',
	'hero.title.argentina': 'ARGENTINA',
	'hero.title.part2': 'Y',
	'hero.title.brasil': 'BRASIL',
	'hero.title.part3': 'SIN COMPLICACIONES',
	'hero.empresa.text1': 'Con',
	'hero.empresa.caipiEmpresa': 'CAIPI EMPRESA',
	'hero.empresa.text2': 'gestionás',
	'hero.empresa.text3': 'tus operaciones comerciales.',
	'hero.empresa.button': 'INGRESO PARA EMPRESAS',
	'hero.app.text1': 'Viajá, pagá y transferí por',
	'hero.app.pix': 'PIX',
	'hero.app.text2': 'sin complicarte.',
	'hero.app.text3': '¡Hacelo todo con',
	'hero.app.caipiApp': 'CAIPI APP',
	'hero.app.button': 'DESCARGÁ CAIPI',
	'hero.backgroundTitle': '¡Pix enviado!',
	'hero.backgroundSubtitle': 'Transferencia realizada con éxito',
	'discover.title': 'Descubrí caipi',
	'discover.paragraph1': 'Solución web app para <span class="font-gothamBlack">empresas</span>.',
	'discover.paragraph2':
		'Caipi convierte pesos argentinos y reales brasileños <span class="font-gothamBlack">al instante</span> <br /> <span class="font-gothamBlack">sin comisiones</span> y al mejor tipo de cambio.',
	'discover.useCaipi': 'Quiero usar caipi',
	'discover.useCaipiEnterprise': 'Quiero usar caipi en mi empresa',
	'benefits.title': '¿Querés saber los beneficios de Caipi?',
	'benefits.cards.0.title': 'Seguridad en las Transacciones',
	'benefits.cards.0.description':
		'Disfrutá de pagos seguros y confiables, respaldados por tecnología de punta.',
	'benefits.cards.1.title': 'Ahorro de Tiempo y Esfuerzo',
	'benefits.cards.1.description':
		'Simplificá el envío de dinero a Brasil, con simples transferencias, sin costos extras y sin demoras.',
	'benefits.cards.2.title': 'Cambio Automático de Moneda',
	'benefits.cards.2.description':
		'Obtené el mejor tipo de cambio disponible en tiempo real, sin impuestos y sin comisiones.',
	'benefits.cards.3.title': 'Facilidad de Uso',
	'benefits.cards.3.description':
		'La solución es intuitiva y fácil de usar, permitiendo pagos rápidos, sin complicaciones.',
	'benefits.cards.4.title': 'Compatibilidad Financiera',
	'benefits.cards.4.description':
		'Funciona con cualquier cuenta Argentina, brindándote flexibilidad y conveniencia.',
	'form.title': 'Formulario contacto empresa',
	'form.name': 'Nombre',
	'form.email': 'E-mail',
	'form.phone': 'Teléfono',
	'form.category': 'Rubro',
	'form.country': 'Seleccionar país',
	'form.button': '¡Enviar!',
	'doubts.title.part1': '¿Todavía te quedan ',
	'doubts.title.part2': 'dudas?',
	'doubts.subtitle1': 'Estamos siempre a disposición',
	'doubts.subtitle2': '¡Ponete en contacto con nosotros!',
	'footer.subtitle': 'Todos los derechos reservados.'
};
