export default {
	loginEmailLabel: 'Email',
	loginEmailPlaceholder: 'nombre@empresa.com',
	loginPasswordLabel: 'Contraseña',
	loginForgotPassword: '¿Recuperar contraseña?',
	loginBtn: 'Iniciar sesión',
	loginInvalidCredentials: 'Credenciales inválidas',
	// Restore password translations
	restorePasswordTitle: 'Recuperar contraseña',
	restorePasswordSubtitle: 'Ingresa tu email para recibir instrucciones de recuperación',
	restorePasswordEmailLabel: 'Email',
	restorePasswordEmailPlaceholder: 'nombre@empresa.com',
	restorePasswordBtn: 'Enviar instrucciones',
	restorePasswordSuccess: 'Se han enviado las instrucciones a tu email',
	restorePasswordError: 'Error al enviar las instrucciones',
	restorePasswordEmailError: 'Verifique que su email esté bien escrito',
	restorePasswordBackToLogin: 'Volver al login',
	emailRequired: 'El email es obligatorio',
	// Change password translations
	changePasswordTitle: 'Cambiar contraseña',
	changePasswordSubtitle: 'Ingresa tu nueva contraseña',
	changePasswordNewLabel: 'Nueva contraseña',
	changePasswordConfirmLabel: 'Confirmar contraseña',
	changePasswordBtn: 'Cambiar contraseña',
	changePasswordSuccess: 'Contraseña cambiada exitosamente',
	changePasswordError: 'Error al cambiar la contraseña',
	changePasswordBackToLogin: 'Volver al login',
	passwordRequired: 'La contraseña es obligatoria',
	confirmPasswordRequired: 'Confirmar contraseña es obligatorio',
	passwordMismatch: 'Las contraseñas no coinciden',
	tokenRequired: 'Token de autorización requerido',
	// Confirm email translations
	confirmEmailTitle: 'Confirmar email',
	confirmEmailSuccess: 'Email confirmado exitosamente',
	confirmEmailError: 'Error al confirmar email',
	confirmEmailSuccessMessage: 'Tu email ha sido confirmado. Ya puedes iniciar sesión en tu cuenta.',
	confirmEmailErrorMessage: 'Hubo un error al confirmar tu email. Intenta nuevamente o contacta soporte.',
	confirmEmailRedirectMessage: 'Serás redirigido al login en unos segundos...',
	confirmEmailGoToLogin: 'Ir al login',
	confirmEmailGoToHome: 'Ir al inicio'
};
