export default {
	newPaymentBreadcrumb: 'Nuevo',
	newPaymentDestinationAccount: 'Cuenta de destino',
	newPaymentSourceCurrency: 'Moneda de origen',
	newPaymentDestinationCurrency: 'Moneda de destino',
	newPaymentValueToReceive: 'Valor a recibir',
	newPaymentPair: 'Moneda origen -> destino',
	newPaymentType: 'Tipo',
	newPaymentClientNameReference: 'Nombre cliente',
	newPaymentClientEmailReference: 'Email cliente',
	newPaymentClientPhoneReference: 'Teléfono cliente',
	newPaymentCodeReference: 'Cód. referencia',
	newPaymentConceptReference: 'Concepto',
	newPaymentFileReference: 'Archivo',
	newPaymentGenerateBtn: 'Generar link de pago',
	newPaymentOkBtn: 'Terminar',
	newPaymentSuccess: 'Pago creado',
	newPaymentSourceCurrencyMissing: 'Seleccione una moneda de origen',
	newPaymentDestinationCurrencyMissing: 'Seleccione una moneda de destino',
	newPaymentInvalidAmount: 'Ingrese un valor a recibir válido',
	newPaymentEmailPagador: 'Email del pagador',
	newPaymentCpfPagador: 'CPF del pagador',
	newPaymentExpirationMsg: "El QR expira en {minutes}m {seconds}s",
	newPaymentQrBtn: "Generar QR",
	newPaymentCuil: "CUIL/CUIT del pagador",
};
