export default {
	paymentsBreadcrumb: 'Transacciones',
	newPaymentBtn: 'Generar Nuevo Cobro / Pago',
	exportDataBtn: 'Exportar Datos',
	paymentsSearchPlaceholder: 'Buscar por cliente',
	showFilters: 'Mostrar filtros',
	hideFilters: 'Ocultar filtros',
	statusFilter: 'Filtrar por estado',
	orderLabel: 'Ordenación',
	orderPlaceholder: 'Seleccionar el ordenamiento',
	filterLabel: 'Filtrado',
	dateFilterFrom: 'Desde',
	dateFilterTo: 'Hasta',
	paymentsTableHeadersId: 'ID',
	paymentsTableHeadersCreatedAt: 'Fecha',
	paymentsTableHeadersEstado: 'Estado',
	paymentsTableHeadersMonedaDestino: 'Moneda a recibir',
	paymentsTableHeadersMontoDestino: 'Valor a recibir',
	paymentsTableHeadersCliente: 'Cliente',
	paymentsTableHeadersRef: 'Referencia',
	paymentsTableHeadersConc: 'Concepto',
	paymentsTableHeadersCuenta: 'Cuenta',
	paymentsTableHeadersRefCodigo: 'Cód. ref.',
	paymentsTableHeadersRefNombreCliente: 'Ref. nombre cliente',
	paymentsTableActions: 'Acciones',
	paymentsTablePaymentStatesPending: 'pendiente',
	paymentsTablePaymentStatesProcessing: 'proceso',
	paymentsTablePaymentStatesFinished: 'finalizado',
	paymentsTablePaymentStatesRejected: 'rechazado',
	paymentsTablePaymentStatesCanceled: 'cancelado',

	// QR Payments translations
	qrPaymentsBreadcrumb: 'Cobros QR',
	createQrPaymentBtn: 'Crear Cobro QR',
	viewQrModalTitle: 'Ver QR',
	createQrModalTitle: 'Crear Nuevo Cobro QR',
	qrPaymentsSearchPlaceholder: 'Buscar cobros QR',
	qrPaymentsTableHeadersId: 'ID',
	qrPaymentsTableHeadersEstado: 'Estado',
	qrPaymentsTableHeadersMonto: 'Monto',
	qrPaymentsTableHeadersMoneda: 'Moneda',
	qrPaymentsTableHeadersCreatedAt: 'Fecha',
	qrPaymentsTableHeadersCliente: 'Cliente',
	qrPaymentsTableHeadersConcepto: 'Concepto',
	qrPaymentsTableHeadersReferencia: 'Referencia',
	qrPaymentsTableEstadoProceso: 'proceso',
	qrPaymentsTableEstadoFinalizado: 'finalizado',
	qrPaymentsTableEstadoCancelado: 'cancelado',
	qrPaymentsTableEstadoRechazado: 'rechazado',
	qrPaymentsTableEstadoUsdtReceived: 'USDT recibido',
	qrPaymentsTableEstadoSwapExecuted: 'Swap ejecutado',
	qrPaymentsTableEstadoWithdrawal: 'Retiro realizado',
	createQrAmountLabel: 'Monto del cobro',
	createQrConceptLabel: 'Concepto',
	createQrConceptPlaceholder: 'Descripción del cobro',
	cancelBtn: 'Cancelar',
	createQrBtn: 'Crear cobro',

	// QR translations
	showQrBtn: 'Mostrar QR',
	qrGenerating: 'Generando QR...',
	qrGenerateSuccess: 'QR generado con éxito',
	qrGenerateError: 'Error al generar QR',
	qrConcept: 'QR de Cobro',
	qrReference: 'Referencia',
	qrVariableAmount: 'Valor definido por el cliente',
	qrPrintButton: 'Imprimir QR',
	qrPrintTitle: 'Imprimir QR',
	qrPrintError: 'Error al abrir ventana de impresión',

	// Static QR translations
	staticQrMontoPesos: 'Monto (Pesos)',
	staticQrMontoReales: 'Monto (Reales)',
	staticQrMontoUsdt: 'Monto (USDT)',
	staticQrEstadoPendiente: 'pendiente',
	staticQrEstadoProceso: 'proceso',
	staticQrEstadoFinalizado: 'finalizado',
	staticQrEstadoCancelado: 'cancelado',
	staticQrEstadoError: 'error',
	qrPaymentsTableHeadersEmpresa: 'Empresa',
	acceptBtn: 'Aceptar',
	paymentCancelled: 'Pago cancelado',
	errorCancellingPayment: 'Error al cancelar pago',
	paymentSuccess: 'Pago exitoso',
	paymentFailed: 'Pago fallido',
	closeModal: 'Cerrar',
	cancelPayment: 'Cancelar pago',
	waitingPayment: 'Esperando pago...',
	processing: 'Procesando...',
	viewPaymentDetails: 'Ver detalles',
	cannotCancelPayment: 'Solo se pueden cancelar pagos pendientes',
	paymentDetails: 'Detalles del pago',
	backToList: 'Volver al listado'
};
