export default {
	profileBreadcrumb: 'Perfil',
	profileEnterpriseLabel: 'Empresa',
	profileEnterpriseName: 'Nombre',
	profileAddress: 'Direccion',
	profilePhone: 'Telefono',
	profileAccounts: 'Cuentas Bancarias',
	profileEmailLabel: 'Email',
	profileNamesLabel: 'Nombres',
	profilePassword: 'Contraseña',
	profileRepeatPassword: 'Repetir Contraseña',
	profileSendBtn: 'Enviar',
	profileBtn: 'Perfil',
	profileLogoutBtn: 'Cerrar Sesión',
	profileSuccess: 'Perfil actualizado',
	profileRepeatPasswordError: 'Las contraseñas no coinciden',
	profileUserLabel: "Detalle Usuario",
	profileChangePassword: "Cambiar contraseña",
	profileBankName: 'Nombre del banco',
	profileNoAccounts: 'No hay cuentas asociadas.',
	profileChangeCallback: "Editar",
	profileChangeApiKey: "generar nueva api key",
	profileConfirmTitle: "Generar",
	profileConfirmSubtitle: "¿Estás seguro de generar una nueva api key?",

};
